CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    description VARCHAR(500),
    price DECIMAL(10,2),
    quantity INTEGER,
    status VARCHAR(30),
    created_at TIMESTAMP
);